### PR TITLE
Feature/43 Deleted entryName field in Record class

### LINKED ISSUE #43: Feature: Bucket.writeRecord receives entry name and bucket
### Current problem

This is fine but not aligned with the other SDKs. 
```java
Record record = Record.builder()
            .entryName("sensor-1")
            .timestamp(timestamp)
            .body("Record #1".getBytes())
            .build();

bucket.writeRecord(record);
```

### Possible solution

Preferable interface:

```java
Record record = Record.builder()
            .timestamp(timestamp)
            .body("Record #1".getBytes())
            .build();

bucket.writeRecord("senor-1", record);
```

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Rumpelshtinskiy**
Closes #43 

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Refactoring

### What was changed?

(Describe the changes)

### Related issues

#43 

### Does this PR introduce a breaking change?

Yes

### CODE REVIEW

**Comment by Rumpelshtinskiy** [comment]
@atimin this brunch was started from feature/42 and will rebese with main after feature/42 will merge in main branch

**Comment by atimin** [comment]
@Rumpelshtinskiy , all good with the patch. Could you resolve the conflicts?

**Comment by Rumpelshtinskiy** [comment]
> @Rumpelshtinskiy , all good with the patch. Could you resolve the conflicts?

Sure, but I'm still working on tests

**Comment by Rumpelshtinskiy** [comment]
@atimin done

**Review by atimin — APPROVED** [review]

**Pull request merged**
